on:
  push:
    tags:
      - 'v*.*.*'

name: Build binaries for release

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build in release mode
        run: cargo build --release

      - name: Prefix binary name (unix)
        if: runner.os != 'Windows'
        shell: bash
        run: cp target/release/aoede target/release/${{ runner.os }}-aoede

      - name: Prefix binary name (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Copy-Item target\release\aoede.exe target\release\Windows-aoede.exe

      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            target/release/*-aoede
            target/release/*-aoede.exe
